In [1]:
import numpy as np

In [2]:
list1= [1,2,3]
list1

[1, 2, 3]

In [3]:
np.array(list1)

array([1, 2, 3])

In [4]:
matrix=[[1,2,3],[3,4,5],[6,7,8]]
matrix

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [5]:
np.array(matrix)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(0,20,3)


array([ 0,  3,  6,  9, 12, 15, 18])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [13]:
np.linspace(1,6,3)

array([1. , 3.5, 6. ])

In [14]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [15]:
np.random.rand(5)

array([0.55458356, 0.2730401 , 0.22583782, 0.83466239, 0.73498574])

In [16]:
np.random.rand(5,10)

array([[0.59915736, 0.80711103, 0.14349105, 0.05542415, 0.80744248,
        0.17021785, 0.16773249, 0.21981275, 0.19389335, 0.59941287],
       [0.09870425, 0.20668   , 0.35847031, 0.3200268 , 0.30120575,
        0.84337629, 0.14292032, 0.0485658 , 0.72757208, 0.4108775 ],
       [0.28333214, 0.72970693, 0.28876766, 0.16342322, 0.85464652,
        0.13283468, 0.92110407, 0.58061404, 0.25814678, 0.0879779 ],
       [0.83336973, 0.82324394, 0.14526709, 0.35831152, 0.10180645,
        0.59891102, 0.86159719, 0.46401912, 0.70920427, 0.86337146],
       [0.10259388, 0.93376315, 0.82552349, 0.47630287, 0.03523275,
        0.14798209, 0.23264503, 0.46257699, 0.09145735, 0.28017437]])

In [17]:
np.random.randn(2)

array([-0.38853539, -0.24173751])

In [18]:
np.random.randint(1,100)

56

In [19]:
np.random.randint(1,100,44)

array([80, 45, 84, 44, 45, 68, 46, 95, 48, 98,  4, 15, 12, 23, 44,  2, 48,
       47, 58, 92, 87, 48,  2, 10, 83, 85, 99, 49, 42,  3, 33, 98, 44, 61,
       54, 45,  1, 39, 12, 70, 34, 93, 30,  8])

In [20]:
np.random.randint(1,100)

95

In [21]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ar=np.arange(0,25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ar.max()

24

In [ ]:
ar.min()

0

In [26]:
ar.argmax()

24

In [27]:
ar.argmin()

0

In [28]:
rndm=np.random.randint(0,25,20)

In [29]:
ar.shape

(25,)

In [30]:
rndm

array([18, 17,  1,  0,  6, 20, 10, 12,  4,  2, 16, 17,  0,  0,  8,  3, 10,
       17,  9, 20])

In [31]:
ar.reshape(25,1).shape

(25, 1)

In [32]:
ar.dtype

dtype('int64')

In [33]:
rndm.argmax()

5

In [34]:
rndm.argmin()

3

In [35]:
ar[5]

5

In [36]:
rndm[2]

1

In [37]:
rndm[0:6]

array([18, 17,  1,  0,  6, 20])

In [38]:
rndm[9:11]

array([ 2, 16])

In [39]:
rndm[:5]

array([18, 17,  1,  0,  6])

In [40]:
rndm[0:1]=50

In [41]:
rndm

array([50, 17,  1,  0,  6, 20, 10, 12,  4,  2, 16, 17,  0,  0,  8,  3, 10,
       17,  9, 20])

In [42]:
rndm[2:4]=101

In [43]:
rndm

array([ 50,  17, 101, 101,   6,  20,  10,  12,   4,   2,  16,  17,   0,
         0,   8,   3,  10,  17,   9,  20])

In [44]:
rndm.reshape(5,4)

array([[ 50,  17, 101, 101],
       [  6,  20,  10,  12],
       [  4,   2,  16,  17],
       [  0,   0,   8,   3],
       [ 10,  17,   9,  20]])

In [45]:
rndm.reshape(1,20)

array([[ 50,  17, 101, 101,   6,  20,  10,  12,   4,   2,  16,  17,   0,
          0,   8,   3,  10,  17,   9,  20]])

In [46]:
rndm1=rndm.copy()

In [47]:
rndm1

array([ 50,  17, 101, 101,   6,  20,  10,  12,   4,   2,  16,  17,   0,
         0,   8,   3,  10,  17,   9,  20])

In [48]:
rndm1[:]=100

In [49]:
rndm1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [50]:
rndm2=rndm.copy()

In [51]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [52]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [53]:
arr_2d[2,:]

array([35, 40, 45])

In [54]:
arr_2d>35

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [55]:
rndm<7

array([False, False, False, False,  True, False, False, False,  True,
        True, False, False,  True,  True, False,  True, False, False,
       False, False])

In [56]:
arr_2d[arr_2d>4]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [57]:
arr_2d>4

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [58]:
rndm[rndm<7]

array([6, 4, 2, 0, 0, 3])

In [59]:
bool_arr=arr_2d>4

In [61]:
bool_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [60]:
import numpy as np

In [62]:
ar2=np.arange(0,20)

In [63]:
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
ar2*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [65]:
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [66]:
ar2/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8])

In [67]:
ar2/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf])

In [68]:
ar2+ar2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [69]:
ar2[0:1]/0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan])

In [70]:
ar2*ar2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [71]:
ar2/ar2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
ar2^3

array([ 3,  2,  1,  0,  7,  6,  5,  4, 11, 10,  9,  8, 15, 14, 13, 12, 19,
       18, 17, 16])

In [73]:
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
ar3=np.random.randint(0,10,10)

In [75]:
ar3

array([7, 0, 1, 8, 0, 9, 6, 3, 5, 4])

In [76]:
ar=np.ones(10)

In [77]:
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
ar4=np.zeros(10)

In [79]:
ar4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
ar=np.ones(10)

In [81]:
ar*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [82]:
ar=np.arange(10,51,2)

In [83]:
ar

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [84]:
ar3=np.arange(0,9)

In [85]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [86]:
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
ar3.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
np.random.rand(1)

array([0.4482689])

In [90]:
np.random.randn(25)

array([-1.36540442e-01, -1.37034015e+00,  6.64686952e-01,  5.39541640e-01,
        4.85629757e-01, -1.74051544e-01, -7.48473765e-02, -1.17142460e+00,
        1.57321625e+00, -4.26585680e-01, -6.75202023e-01, -1.35129852e+00,
        1.11441838e+00,  5.84516051e-01, -1.62092201e+00,  1.65564047e-01,
        8.70840176e-01, -1.40964483e+00,  3.52895149e-01, -1.81090508e+00,
        3.84476430e-01, -1.38522150e-03, -9.47100671e-02,  1.06069461e+00,
        1.26865779e+00])

In [91]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [92]:
ah=np.arange(1,101)

In [93]:
ah1=ah/100

In [94]:
ah1.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [95]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [96]:
mat=np.arange(1,26).reshape(5,5)

In [97]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
mat[12:26]

array([], shape=(0, 5), dtype=int64)

In [99]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [100]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [101]:
mat1=mat[12:]

In [102]:
mat1

array([], shape=(0, 5), dtype=int64)

In [103]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [104]:
mat[3:4,4:]

array([[20]])

In [105]:
mat[3,4]

20

In [106]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [107]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [108]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [109]:
mat[3:,:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:
mat[4]

array([21, 22, 23, 24, 25])

In [111]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [112]:
sum(sum(mat))

325

In [113]:
np.sum(mat)

325

In [114]:
np.std(mat)

7.211102550927978

In [115]:
sum(mat)

array([55, 60, 65, 70, 75])

In [116]:
mat<6


array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [117]:
mat[mat<6]

array([1, 2, 3, 4, 5])